import express from 'express';
import { createServer as createViteServer } from 'vite';
import path from 'path';
import { fileURLToPath } from 'url';
import multer from 'multer';
import mammoth from 'mammoth';
import htmlToDocx from 'html-to-docx';
import { decode } from 'html-entities';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const upload = multer({ storage: multer.memoryStorage() });

async function startServer() {
  const app = express();
  const PORT = Number(process.env.PORT) || 3000;

  app.use(express.json());

  // API Routes
  app.post('/api/extract-text', upload.single('file'), async (req, res) => {
    try {
      if (!req.file) {
        return res.status(400).json({ error: 'No file uploaded' });
      }

      const result = await mammoth.extractRawText({ buffer: req.file.buffer });
      res.json({ text: result.value });
    } catch (error) {
      console.error('Extraction error:', error);
      res.status(500).json({ error: 'Failed to extract text' });
    }
  });

  app.post('/api/generate-annotated', async (req, res) => {
    try {
      const { text, findings } = req.body;
      
      const fullHtml = `
        <div style="font-family: 'Arial';">
          <h1 style="text-align: center;">TEM Analysis Annotated Report</h1>
          <p style="text-align: center; color: #64748b;">Flight Operations Safety Analysis Findings</p>
          <hr />
          <div style="line-height: 1.6;">
            ${text}
          </div>
          <br />
          <hr />
          <h2>Summary Table</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background-color: #f1f5f9;">
                <th style="border: 1px solid #cbd5e1; padding: 8px;">Finding</th>
                <th style="border: 1px solid #cbd5e1; padding: 8px;">Category</th>
                <th style="border: 1px solid #cbd5e1; padding: 8px;">Context/Reason</th>
              </tr>
            </thead>
            <tbody>
              ${findings.map((f: any) => `
                <tr>
                  <td style="border: 1px solid #cbd5e1; padding: 8px;">${f.text}</td>
                  <td style="border: 1px solid #cbd5e1; padding: 8px;">
                    <span style="color: ${f.category === 'Threat' ? '#2563eb' : f.category === 'Error' ? '#eab308' : '#dc2626'}">
                      ${f.category}
                    </span>
                  </td>
                  <td style="border: 1px solid #cbd5e1; padding: 8px; font-size: 11px;">${f.reason}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <p style="font-size: 10px; color: #94a3b8; margin-top: 20px;">
            Generated by 6E_TEM Safety Analysis Engine • Framework-compliant TEM Report
          </p>
        </div>
      `;

      const buffer = await htmlToDocx(fullHtml, null, {
        table: { row: { cantSplit: true } },
        footer: true,
        pageNumber: true,
      });
      
      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
      res.setHeader('Content-Disposition', 'attachment; filename=TEM_Safety_Report.docx');
      res.send(buffer);
    } catch (error) {
      console.error('Generation error:', error);
      res.status(500).json({ error: 'Failed to generate document' });
    }
  });

  // Helper function removed in favor of direct HTML conversion


  // Vite middleware for development
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
